Verday="2015-2016"
Partners="YiYanYun.Com - HuLian.WS -"
lang_1="Install"
lang_2="Alone Install" 
lang_3="Install ALL" 
lang_4="Nothing,Exit,Can run 'runsh' Comeback" 
lang_5="Nothing,Exit,Can run 'sh d.sh' Comeback" 
lang_6="Nothing,Exit,Can run 'sh u.sh' Comeback" 
lang_7="Nothing,Exit,Can run 'runos' Comeback" 
lang_8="Exit Shell Install" 
lang_9="Copyright" 
lang_10="Version By" 
lang_11="Reselect node" 
lang_12="Back" 
lang_13="UpdateDay" 
lang_14="Easypanel_Template" 
lang_15="Language Change" 
lang_16="中文语言" 
lang_17="English Language" 
lang_18="Exit Language Change" 
lang_19="Install Is Error"
lang_20="Install Is OK" 
lang_21="Partners" 
lang_22="Update For:" 
lang_23="You Can run 'runsh' New Version" 
lang_24="No Update,You Can run 'runsh' Comeback" 
lang_25="Update" 
lang_26="Repair function" 
lang_27="Reset Mysql Password" 
lang_28="Singapore node (Hong Kong recommends Machine Selection)"
lang_29="node the United States (foreign advice Machine Selection)"
lang_30="China Node (Recommendation domestic machine selection)"
lang_31="" 
lang_32="" 
lang_33="" 
lang_34="" 
lang_35="" 
lang_36="" 
lang_37=""

lang_OK1="Please visit http://ip:3312/admin to continu"
lang_OK2="easypanel user:admin"
lang_OK3="easypanel pswd:kangle"
lang_OK4="Mysql user:root"
lang_OK5="Mysql pswd:mysql"
Key=(`seq 0 9 | awk 'BEGIN{srand();ORS=""} {b[rand()]=$0} END{for(x in b) print b[x]}'`)
poweredby="
				╦ ╦╦ ╦╦  ╦╔═╗╔╗╔
				╠═╣║ ║║  ║╠═╣║║║
				╩ ╩╚═╝╩═╝╩╩ ╩╝╚╝

	"$lang_9" © "$Verday" "$lang_10":"$Ver" "$lang_13":"$Day"
				 ※※※※※※※※※※
				※ "$lang_21" ※
※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※※
"$Partners"" 
